webempresa/blog/urls.py
from django.urls import path
from . import views

urlpatterns = [

    #Paths del Blog
    path('blog/', views.blog, name="blog"),
    path ('blog/category/<int:category_id>/', views.category, name="category"),
    #<>/ es un campo dinamico. Con eso pasamos un parametro, que la url pasará a la vista como category_id
    #Es importante que se pasa como cadena de caracteres. Como necesitamos que sea un int (xq el id es un int)
    #agregamos int: para castear.
]

webempresa/webempresa/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings

urlpatterns = [

    #Paths del core
    path('', include('core.urls')),
    #Paths de services
    path('', include('services.urls')),
    #Paths del blog
    path('', include('blog.urls')),
    #Paths de pages
    path('page/', include('pages.urls')),
    #Paths de conact
    path('contact/', include('contact.urls')),
    #Path del administrador
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

webempresa/blog/models.py
from django.db import models
from django.utils.timezone import now #Imporza libreria de fechas
from django.contrib.auth.models import User #importar usuarios creados con el panel de admin

# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=100, verbose_name="Nombre")
    created = models.DateTimeField(auto_now_add=True, verbose_name="Fecha de Creación")
    updated = models.DateTimeField(auto_now=True, verbose_name="Fecha de Modificación")

    class Meta:
        verbose_name = "categoria"
        verbose_name_plural = "categorias"
        ordering = ['-created']

    def __str__(self):
        return self.name


class Post(models.Model):
    title = models.CharField(max_length=200, verbose_name="Título")
    content = models.TextField(verbose_name="Contenido")
    published = models.DateTimeField(verbose_name="Fecha de Publicación", default=now())
    image = models.ImageField(verbose_name="Imagen", upload_to="blog", null=True, blank=True)
    #Enlazar con Foreign Key en cascada
    author = models.ForeignKey(User, verbose_name="Autor", on_delete=models.CASCADE)
    categories = models.ManyToManyField(Category, verbose_name="Categorias", related_name="get_posts")
    created = models.DateTimeField(verbose_name="Fecha de Creación", auto_now_add=True)
    updated = models.DateTimeField(auto_now=True, verbose_name="Fecha de Modificación")

    class Meta:
        verbose_name = "entrada"
        verbose_name_plural = "entradas"
        ordering = ['-created']

    def __str__(self):
        return self.title

webempresa/blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import Post, Category
#Importamos el modelo Post

# Create your views here.
def blog(request):
    post = Post.objects.all()
    #recoletamos todos los posts
    return render(request, "blog/blog.html", {'posts': post})

def category(request, category_id):
    category = get_object_or_404(Category, id=category_id)
    #category_id es un campo que se genera automaticamente al momento de crear un registro.
    #Es enviado a nuestra vista por nuestra URL, y lo vamos a utilizar para filtrar.
    #category = Category.objects.get(id= category_id) FORMA SIMPLE DE HACERLO.
    #FORMA ELEGANTE DE EN CASO DE ERROR USAR UN 404
    #get permite recoger un unico registro, filtrando por id.
    #posts = Post.objects.filter(categories=category) #filtramos por categoria
    #return render(request, "blog/category.html", {'category': category, 'posts': posts})
    #Forma atajo mágico:
    return render(request, "blog/category.html", {'category': category})

webempresa/blog/templates/blog/blog.html
{% extends "core/base.html" %}
{% load static %}

{% block content %}
  {% for post in posts %}
    <section class="page-section cta">
      <div class="container">
        <div class="row">
          <div class="col-xl-9 mx-auto">
            <div class="cta-innerv text-center rounded">
              <h2 class="section-heading mb-5">
                <span class="section-heading-upper">{{post.published|date:"SHORT_DATE_FORMAT"}}</span>
                {% comment %} con shot_time formateamos la fecha {% endcomment %}
                <span class="section-heading-lower">{{post.title}}</span>
              </h2>
              <p class="mb-0">
                <img class="mx-auto d-flex rounded img-fluid mb-3 mb-lg-0" src="{{post.image.url}}" alt="">
              </p>
              <p class="mb-0 mbt">
                {{post.content|linebreaks}} 
                {% comment %} linebreaks para q muestre saltos de linea {% endcomment %}
              </p>
              <p class="mb-0 mbt">
                <span class="section-heading-under">Publicado por <em><b>{{post.author}}</b></em> en 
                {% comment %} <em><a href="#" class="link">General</a>, <a href="#" class="link">Ofertas</a></em></span> {% endcomment %}
                  <em> 
                    {% for category in post.categories.all %}
                    {% comment %} post.categories.all sirve para q haga el query de un campo many to many, sino no funca {% endcomment %}
                      <a href="{% url 'category' category.id %}" class= "link"> {{category.name}}</a> {% if not forloop.last %},{% endif %}
                    {% comment %} sino es el ultimo, agregamos coma {% endcomment %}
                    {% endfor %}
                  </em>

              </p>
            </div>

          </div>
        </div>
      </div>
    </section>
  {% endfor %}
{% endblock content %}
    

webempresa/blog/templates/blog/category.html
{% extends "core/base.html" %}
{% load static %}

{% block content %}
  {% for post in category.get_posts.all %}
  {% comment %} category.post_set va a buscar todas las instancias del segundo modelo relacionado con el primero
   pURA MAGIA{% endcomment %}
    <section class="page-section cta">
      <div class="container">
        <div class="row">
          <div class="col-xl-9 mx-auto">
            <div class="cta-innerv text-center rounded">
              <h2 class="section-heading mb-5">
                <span class="section-heading-upper">{{post.published|date:"SHORT_DATE_FORMAT"}}</span>
                {% comment %} con shot_time formateamos la fecha {% endcomment %}
                <span class="section-heading-lower">{{post.title}}</span>
              </h2>
              <p class="mb-0">
                <img class="mx-auto d-flex rounded img-fluid mb-3 mb-lg-0" src="{{post.image.url}}" alt="">
              </p>
              <p class="mb-0 mbt">
                {{post.content|linebreaks}} 
                {% comment %} linebreaks para q muestre saltos de linea {% endcomment %}
              </p>
              <p class="mb-0 mbt">
                <span class="section-heading-under">Publicado por <em><b>{{post.author}}</b></em> en 
                {% comment %} <em><a href="#" class="link">General</a>, <a href="#" class="link">Ofertas</a></em></span> {% endcomment %}
                  <em>
                    {% for category in post.categories.all %}
                    {% comment %} post.categories.all sirve para q haga el query de un campo many to many, sino no funca {% endcomment %}
                    <a href="{% url 'category' category.id %}" class= "link"> {{category.name}}</a> {% if not forloop.last %},{% endif %}
                    {% comment %} sino es el ultimo, agregamos coma {% endcomment %}
                    {% endfor %}
                  </em>

              </p>
            </div>

          </div>
        </div>
      </div>
    </section>
  {% endfor %}
{% endblock content %}
    